# Generated by Django 3.0.3 on 2020-02-20 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlistapp', '0002_auto_20200220_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='owner',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
