# Generated by Django 2.1.5 on 2020-02-20 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlistapp', '0003_auto_20200220_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='owner',
        ),
        migrations.AddField(
            model_name='wish',
            name='list',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
