# Generated by Django 2.1.5 on 2020-02-20 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0005_auto_20200220_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='list',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
