# Generated by Django 2.1.5 on 2020-02-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0006_auto_20200220_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='list',
            new_name='owner',
        ),
    ]
