# Generated by Django 2.1.5 on 2020-02-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0007_auto_20200220_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
