# Generated by Django 2.1.5 on 2020-02-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0008_auto_20200220_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='description',
        ),
        migrations.AddField(
            model_name='wish',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
